/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Othello_p.OthelloScoreKeeper;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;


/**
 *
 * @author Chris Wells
 */
public class GamePanel extends javax.swing.JPanel implements MouseListener{

    /**
     * Creates new form GamePanel
     */
    OthelloScoreKeeper score;
    BufferedImage background;
    public GamePanel() {
        initComponents();
        try{
            background = ImageIO.read(new File(".\\src\\resources\\img\\23_1920.jpg"));
        } catch (IOException fnf) {
            System.out.println("File(s) not found");
        }
        othelloGrid1.passMouseListeners(this);
        score = othelloGrid1.passScoreKeeper();
        lblScoreBlackVal.setText(""+score.getPointBlack());
        lblScoreWhiteVal.setText(""+score.getPointWhite());
    }
    
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.drawImage(background, 0, 0, this.getWidth(), this.getHeight(), this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImageBlack = new javax.swing.JLabel();
        lblImageWhite = new javax.swing.JLabel();
        lblScoreBlack = new javax.swing.JLabel();
        lblScoreWhite = new javax.swing.JLabel();
        lblScoreBlackVal = new javax.swing.JLabel();
        lblScoreWhiteVal = new javax.swing.JLabel();
        othelloGrid1 = new OthelloGrid.OthelloGrid();

        lblImageBlack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris Wells\\Documents\\NetBeansProjects\\OthelloPlus_WithGUI\\src\\resources\\img\\black.png")); // NOI18N
        lblImageBlack.setText("name01");

        lblImageWhite.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris Wells\\Documents\\NetBeansProjects\\OthelloPlus_WithGUI\\src\\resources\\img\\white.png")); // NOI18N
        lblImageWhite.setText("name02");

        lblScoreBlack.setText("Score :");

        lblScoreWhite.setText("Score :");

        lblScoreBlackVal.setText("XXX");

        lblScoreWhiteVal.setText("XXX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblScoreBlack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(lblScoreBlackVal)
                                .addGap(290, 290, 290))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblImageBlack))
                                    .addComponent(lblImageWhite))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(othelloGrid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblScoreWhite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblScoreWhiteVal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImageBlack)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblScoreBlackVal)
                            .addComponent(lblScoreBlack))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImageWhite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblScoreWhiteVal)
                            .addComponent(lblScoreWhite)))
                    .addComponent(othelloGrid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImageBlack;
    private javax.swing.JLabel lblImageWhite;
    private javax.swing.JLabel lblScoreBlack;
    private javax.swing.JLabel lblScoreBlackVal;
    private javax.swing.JLabel lblScoreWhite;
    private javax.swing.JLabel lblScoreWhiteVal;
    private OthelloGrid.OthelloGrid othelloGrid1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void mousePressed(MouseEvent e) {
        lblScoreBlackVal.setText(""+score.getPointBlack());
        lblScoreWhiteVal.setText(""+score.getPointWhite());
    }

    @Override
    public void mouseReleased(MouseEvent e) {
       // throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void mouseExited(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

}
