/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.awt.Color;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Chris Wells
 */
public class OnePlayerPreGameMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu2
     */
    MenuController menuCon;
    Dimension gameMenuDimen;
    private int sizeOfBoard;
    private int whiteAI;
    private int blackAI;
    
    public OnePlayerPreGameMenu(MenuController mc){
        sizeOfBoard = 8;
        whiteAI = 0;
        blackAI = -1;
        menuCon = mc;
        gameMenuDimen = new Dimension(menuCon.getWidth(), menuCon.getHeight());
        
        initComponents();
        btnPiece.setImage(".\\src\\resources\\img\\black.png");
        
    }
    
    public void setBackGround(String imgLoc){
        //backPanel.setImage(imgLoc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGroundImage = new Menu.imagePanel();
        contentPane = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        btnReturnToMainMenu = new javax.swing.JLabel();
        lblSelectPiece = new javax.swing.JLabel();
        btnPiece = new Menu.imagePanel();
        lblSelectAi = new javax.swing.JLabel();
        btnAi = new javax.swing.JLabel();
        lblSelectSize = new javax.swing.JLabel();
        btnSize = new javax.swing.JLabel();
        bntPlay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.desktop);
        setMaximumSize(gameMenuDimen);
        setMinimumSize(gameMenuDimen);
        setPreferredSize(gameMenuDimen);
        setResizable(false);
        setUndecorated(true);

        contentPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contentPane.setOpaque(false);

        lblHeader.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblHeader.setText("One Player Setup");

        btnReturnToMainMenu.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnReturnToMainMenu.setText("Main Menu");
        btnReturnToMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnReturnToMainMenuMousePressed(evt);
            }
        });

        lblSelectPiece.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblSelectPiece.setText("Select Piece :");

        btnPiece.setMaximumSize(new java.awt.Dimension(51, 51));
        btnPiece.setMinimumSize(new java.awt.Dimension(51, 51));
        btnPiece.setPreferredSize(new java.awt.Dimension(51, 51));
        btnPiece.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPieceMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnPieceLayout = new javax.swing.GroupLayout(btnPiece);
        btnPiece.setLayout(btnPieceLayout);
        btnPieceLayout.setHorizontalGroup(
            btnPieceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );
        btnPieceLayout.setVerticalGroup(
            btnPieceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblSelectAi.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblSelectAi.setText("Select Ai :");

        btnAi.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        btnAi.setText("easy");
        btnAi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAiMousePressed(evt);
            }
        });

        lblSelectSize.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblSelectSize.setText("Select Size :");

        btnSize.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        btnSize.setText("8");
        btnSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSizeMousePressed(evt);
            }
        });

        bntPlay.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        bntPlay.setText("PLAY");
        bntPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bntPlayMousePressed(evt);
            }
        });

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addComponent(bntPlay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReturnToMainMenu))
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeader)
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addComponent(lblSelectPiece)
                                .addGap(18, 18, 18)
                                .addComponent(btnPiece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addComponent(lblSelectAi)
                                .addGap(18, 18, 18)
                                .addComponent(btnAi))
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addComponent(lblSelectSize)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSize)))
                        .addGap(0, 420, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addGap(67, 67, 67)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSelectPiece, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPiece, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectAi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(216, 216, 216)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturnToMainMenu)
                    .addComponent(bntPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout BackGroundImageLayout = new javax.swing.GroupLayout(BackGroundImage);
        BackGroundImage.setLayout(BackGroundImageLayout);
        BackGroundImageLayout.setHorizontalGroup(
            BackGroundImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundImageLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        BackGroundImageLayout.setVerticalGroup(
            BackGroundImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundImageLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-640)/2, 800, 640);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPieceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPieceMousePressed
        // TODO add your handling code here:
        if(blackAI == -1){
            btnPiece.setImage(".\\src\\resources\\img\\white.png");
            blackAI = whiteAI;
            whiteAI = -1;
        }
        else
        {
            btnPiece.setImage(".\\src\\resources\\img\\black.png");
            whiteAI = blackAI;
            blackAI = -1;
        }
        
    }//GEN-LAST:event_btnPieceMousePressed

    private void btnAiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAiMousePressed
        // TODO add your handling code here:
        if(blackAI >= 0){
            if(blackAI == 0){
                blackAI = 1;
                btnAi.setText("med");
            }else if(blackAI == 1){
                blackAI = 2;
                btnAi.setText("hard");
            }else{
                blackAI = 0;
                btnAi.setText("easy"); 
           }
        }else{
            if(whiteAI == 0){
                whiteAI = 1;
                btnAi.setText("med");
            }else if(whiteAI == 1){
                whiteAI = 2;
                btnAi.setText("hard");
            }else{
                whiteAI = 0;
                btnAi.setText("easy"); 
           }
        }
    }//GEN-LAST:event_btnAiMousePressed

    private void btnSizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSizeMousePressed
        // TODO add your handling code here:
        if(sizeOfBoard == 8){
            sizeOfBoard = 10;
            btnSize.setText("10");
        }else if(sizeOfBoard == 10){
            sizeOfBoard = 12;
            btnSize.setText("12");
        }else{
            sizeOfBoard = 8;
            btnSize.setText("8");
        }
           
    }//GEN-LAST:event_btnSizeMousePressed

    private void btnReturnToMainMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnToMainMenuMousePressed
        // TODO add your handling code here:
        menuCon.loadMainMenu();
        menuCon.closeOnePlayerMenu();
    }//GEN-LAST:event_btnReturnToMainMenuMousePressed

    private void bntPlayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntPlayMousePressed
        menuCon.gameSettings( sizeOfBoard, whiteAI, blackAI);
        menuCon.loadGameWindow();
        menuCon.closeOnePlayerMenu();
    }//GEN-LAST:event_bntPlayMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Menu.imagePanel BackGroundImage;
    private javax.swing.JLabel bntPlay;
    private javax.swing.JLabel btnAi;
    private Menu.imagePanel btnPiece;
    private javax.swing.JLabel btnReturnToMainMenu;
    private javax.swing.JLabel btnSize;
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblSelectAi;
    private javax.swing.JLabel lblSelectPiece;
    private javax.swing.JLabel lblSelectSize;
    // End of variables declaration//GEN-END:variables
}
