/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author Chris Wells
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    private int splashHeight;
    private int splashWidth;
    private BufferedImage splash;
    private Graphics image;
    MenuController menuCon;
    
    public Splash(MenuController mc) {
        try{
            splash = ImageIO.read(getClass().getResource("/resources/img/Othello_Splash.png"));
        } catch (IOException fnf) {
            System.out.println("File(s) not found");
        }
        menuCon = mc;
        splashHeight = menuCon.getHeight()/2;
        splashWidth = menuCon.getWidth()/2;
        
        my_initComponents();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanSplash = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 640));
        setResizable(false);
        setUndecorated(true);

        javax.swing.GroupLayout jPanSplashLayout = new javax.swing.GroupLayout(jPanSplash);
        jPanSplash.setLayout(jPanSplashLayout);
        jPanSplashLayout.setHorizontalGroup(
            jPanSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanSplashLayout.setVerticalGroup(
            jPanSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanSplash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanSplash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-640)/2, 800, 640);
    }// </editor-fold>//GEN-END:initComponents

    private void my_initComponents() {

        jPanSplash = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g)
            {
            super.paintComponent(g);
            g.drawImage(splash, 0,0, splashWidth,splashHeight,null);
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(splashWidth, splashHeight));
        setResizable(false);
        setUndecorated(true);

        javax.swing.GroupLayout jPanSplashLayout = new javax.swing.GroupLayout(jPanSplash);
        jPanSplash.setLayout(jPanSplashLayout);
        jPanSplashLayout.setHorizontalGroup(
            jPanSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, splashWidth, Short.MAX_VALUE)
        );
        jPanSplashLayout.setVerticalGroup(
            jPanSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, splashHeight, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanSplash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanSplash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-splashWidth)/2, (screenSize.height-splashHeight)/2, splashWidth, splashHeight);
    }
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanSplash;
    // End of variables declaration//GEN-END:variables
}
