/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Chris Wells
 */
public class WinningFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu2
     */
    MenuController menuCon;
    
    public WinningFrame(MenuController mc, int winner){
        menuCon = mc;
        initComponents();
        backPanel.setImage("blank.png");
        
        if(winner == 1)
            lblWinner.setText("Black Player was the Winner!");
        if(winner == 2)
            lblWinner.setText("White Player was the Winner!");
        if(winner == 0)
            lblWinner.setText("The Game ended in a Draw!");
        
    }
    
    public void setBackGround(String imgLoc){
        backPanel.setImage(imgLoc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new imagePanel("blank.png");
        btnMainMenu = new javax.swing.JLabel();
        lblWinner = new javax.swing.JLabel();
        btnPlayAgain = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(600, 20));
        setResizable(false);
        setUndecorated(true);

        backPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 6, true));
        backPanel.setPreferredSize(new java.awt.Dimension(800, 200));

        btnMainMenu.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnMainMenu.setText("Main Menu");
        btnMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMainMenuMousePressed(evt);
            }
        });

        lblWinner.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblWinner.setText("XXXXXXXXXXXXX");

        btnPlayAgain.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnPlayAgain.setText("Play Again");
        btnPlayAgain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPlayAgainMousePressed(evt);
            }
        });

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblWinner)
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addComponent(btnPlayAgain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMainMenu)))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lblWinner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlayAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-608)/2, (screenSize.height-122)/2, 608, 122);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayAgainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayAgainMousePressed
        // TODO add your handling code here:
        menuCon.closeGameWindow();
        menuCon.loadGameWindow();
        this.dispose();
    }//GEN-LAST:event_btnPlayAgainMousePressed

    private void btnMainMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMainMenuMousePressed
        // TODO add your handling code here:
        menuCon.closeGameWindow();
        menuCon.loadMainMenu();
        this.dispose();
    }//GEN-LAST:event_btnMainMenuMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Menu.imagePanel backPanel;
    private javax.swing.JLabel btnMainMenu;
    private javax.swing.JLabel btnPlayAgain;
    private javax.swing.JLabel lblWinner;
    // End of variables declaration//GEN-END:variables
}
